export interface HelpDefinition {
  title: string;
  purpose: string;
  sourceOrDefault: string;
  unit?: string;
  impact: string;
  limitation?: string;
}

export const helpText: Record<string, HelpDefinition> = {
  dataset: { title: '数据集', purpose: '指定本次分析或求解使用的数据版本。', sourceOrDefault: '默认选择已验收基准数据。', impact: '所有任务结果均绑定数据集版本。', limitation: '合成演示数据仅用于订单、产能和考勤分析，不进入现有 MIP 求解。' },
  timeLimit: { title: '求解时限', purpose: '限制单次求解的最长运行时间。', sourceOrDefault: '由求解器任务默认参数提供，用户可在接口约束内调整。', unit: 's', impact: '达到时限后保留求解器返回的可行解和终止状态。', limitation: '超过服务端上限的数值会被截断。' },
  actor: { title: '操作人', purpose: '记录提交、复核或变更的本机操作人标识。', sourceOrDefault: '演示环境默认使用“本机计划员”。', impact: '与角色和原因共同写入本机审计记录。', limitation: '本机演示没有接入统一身份认证。' },
  reason: { title: '操作原因', purpose: '说明操作的业务依据，便于复核和追溯。', sourceOrDefault: '由操作人填写。', impact: '修改、核验和审批操作必须填写。', limitation: '不得填写密码、令牌等敏感凭证。' },
  decisionLabGroup: { title: '方案比较组', purpose: '筛选规划周期、数据集、需求规模和业务比较标记一致的方案。', sourceOrDefault: '由已登记方案元数据及排班 CSV 计算。', impact: '仅组内方案进入同一 Pareto 前沿。', limitation: '缺少日期范围或需求人班时单独分组；未标注比较组的方案会显示提示。' },
  decisionLabPareto: { title: 'Pareto 非支配方案', purpose: '识别在工时成本代理值和需求覆盖率两项主指标上不存在同时更优方案的结果。', sourceOrDefault: '读取已登记排班 CSV 并调用排班管理分析指标计算。', impact: '覆盖率更高且成本估算不高于另一方案时，该方案可支配另一方案。', limitation: '缺少任一主指标的方案不参与前沿判断；该结果不代表唯一最优方案。' },
  decisionLabCost: { title: '工时成本代理值', purpose: '基于计薪工时与加班工时估算方案间的人力投入差异。', sourceOrDefault: '沿用排班管理分析中的本机演示费率及加班倍率。', unit: '元（模拟）', impact: '作为 Pareto 图的横轴，支持成本与覆盖率之间的方案取舍分析。', limitation: '不是企业工资、财务成本或实付金额；缺少可计算工时时显示无可计算值。' },
  decisionLabScenario: { title: '情景推演', purpose: '以已登记排班方案为基线，提交本机支持的异常或需求变更并查看锁定式增量重排结果。', sourceOrDefault: '事件字段取自所选基线排班 CSV 的员工、产线、日期及班次。', impact: '提交后由 Rust 作业服务管理现有重排任务，成功结果登记为新方案版本。', limitation: '只允许服务端判定兼容的已验收基准或用户导入数据；合成演示数据只用于方案分析。' },
  demandProfile: { title: '需求口径', purpose: '选择独立核验所依据的岗位需求版本。', sourceOrDefault: '默认使用求解任务输入口径。', impact: '口径差异会影响覆盖约束与核验结论。', limitation: '参考口径来自包内已登记岗位需求和运行计划。' },
  sourceType: { title: '数据来源', purpose: '标识数据的来源类型和业务可信边界。', sourceOrDefault: '由数据导入或初始化流程写入。', impact: '数据来源标签随任务、方案和归档记录展示。', limitation: '合成演示和本机模拟记录不代表现场实绩。' },
  importSchema: { title: '导入模板', purpose: '指定文件的字段校验规则。', sourceOrDefault: '根据待导入数据类型选择。', impact: '模板决定必填字段、格式检查和可用范围。', limitation: '通过字段检查不代表数据已接入求解器。' },
  rotationConfigName: { title: '配置名称', purpose: '标识一组产线轮班周期及轮转对象。', sourceOrDefault: '由计划员填写；复制时可按业务范围调整。', impact: '用于配置列表、日历筛选和审计记录。', limitation: '名称不得为空。' },
  rotationLine: { title: '适用产线', purpose: '限定该轮转配置所覆盖的本机产线。', sourceOrDefault: '来自本机轮转字典及初始化演示目录。', impact: '启用日期重叠检查和资格校验均以产线为范围。', limitation: '不代表已连接 MES 产线台账。' },
  rotationObjectType: { title: '轮转对象类型', purpose: '指定按班组或按员工计算轮转周期。', sourceOrDefault: '新建配置默认按班组。', impact: '决定轮转对象选择范围及资格关系校验方式。', limitation: '本机日历模块独立于 MIP 求解输入。' },
  rotationStartDate: { title: '生效日期', purpose: '确定周期第 1 日的日历基准。', sourceOrDefault: '由配置创建人填写。', unit: 'YYYY-MM-DD', impact: '后续日期按自然日差计算周期索引。', limitation: '业务日期按 Asia/Shanghai 使用，不换算为 UTC。' },
  rotationEndDate: { title: '失效日期', purpose: '设置配置可参与日历生成的最后一天。', sourceOrDefault: '留空表示未设定结束日期。', unit: 'YYYY-MM-DD', impact: '失效日期之后不生成该配置日历。', limitation: '填写时不得早于生效日期。' },
  rotationCycleLength: { title: '周期长度', purpose: '设置一个轮转周期包含的自然日数量。', sourceOrDefault: '依据周期明细行数填写。', unit: 'd', impact: '偏移量范围为 0 至周期长度减 1。', limitation: '每个周期日必须且只能配置一个班次或休息。' },
  rotationShiftCode: { title: '班次编码', purpose: '提供周期明细引用的稳定班次标识。', sourceOrDefault: '配置创建人填写。', impact: '班次编码须在本配置内唯一。', limitation: '休息日不使用班次编码。' },
  rotationShiftName: { title: '班次名称', purpose: '提供日历可读的班次名称。', sourceOrDefault: '配置创建人填写。', impact: '日历和配置详情按该名称展示班次。', limitation: '使用简体中文业务名称。' },
  rotationShiftTime: { title: '班次时间', purpose: '确定班次开始与结束的本地时刻。', sourceOrDefault: '格式为 24 小时制 HH:mm。', unit: 'h:mm', impact: '结束时刻早于或等于开始时刻时，按次日结束展示。', limitation: '系统不进行时区换算。' },
  rotationCycleRows: { title: '周期明细', purpose: '逐日定义周期内的班次或休息状态。', sourceOrDefault: '由周期长度生成连续日序号。', unit: '自然日', impact: '查询日期与生效日差值、对象偏移共同决定周期日。', limitation: '周期日序号须从 1 连续递增。' },
  rotationTargets: { title: '轮转对象', purpose: '选择参与本配置的班组或员工并指定周期偏移。', sourceOrDefault: '班组及员工目录来自本机配置数据库。', unit: 'd', impact: '偏移用于错开多个对象的周期起点。', limitation: '对象须有效并具备该产线的岗位资格。' },
  rotationOffset: { title: '周期偏移', purpose: '设置对象相对配置生效日的周期日偏移量。', sourceOrDefault: '默认为 0。', unit: 'd', impact: '日历周期索引按 (日期差 + 偏移) 对周期长度取余。', limitation: '仅允许 0 至周期长度减 1。' },
  rotationReason: { title: '配置操作原因', purpose: '记录创建、编辑、复制、启用或停用的业务依据。', sourceOrDefault: '每次变更由操作人填写。', impact: '与操作人及角色写入本机审计记录。', limitation: '不得填写密码或访问令牌。' },
  rotationCalendarLine: { title: '日历产线筛选', purpose: '选择查看轮转日历的产线。', sourceOrDefault: '来自本机轮转产线目录。', impact: '改变查询范围，不修改任何配置。', limitation: '查询日期范围最多 62 个自然日。' },
  rotationCalendarConfig: { title: '日历配置筛选', purpose: '将日历限定到一项配置；留空时显示该产线有效启用配置。', sourceOrDefault: '随所选产线动态加载。', impact: '用于核对特定轮转配置。', limitation: '停用配置默认不参与查询。' },
  rotationCalendarDate: { title: '日历日期', purpose: '确定月视图或周视图的定位日期。', sourceOrDefault: '默认定位到本机当前日期。', unit: '自然日', impact: '日期变化后重新计算服务端轮转结果。', limitation: '业务日期固定按 Asia/Shanghai 处理。' },
  rotationCalendarPersonnel: { title: '班次人员信息', purpose: '查看该轮转班次对应的员工姓名；悬停可查看员工编号和主要岗位。', sourceOrDefault: '按配置对象从本机未归档员工档案实时读取。', unit: '人', impact: '班组对象展示当前有效成员，个人对象展示该员工信息。', limitation: '该日历按本机轮转配置计算，不代表已审批或实际考勤排班。' },
  employeeId: { title: '员工编号', purpose: '标识本机员工档案并用于资格关系关联。', sourceOrDefault: '创建员工时填写；不可与现存编号重复。', impact: '员工档案、资格关系和轮转配置引用此编号。', limitation: '本机演示编号不代表 HR 主数据。' },
  employeeName: { title: '员工姓名', purpose: '显示员工档案的本机名称。', sourceOrDefault: '由维护人员填写。', impact: '用于员工列表及轮转对象选择。', limitation: '本机初始化名称为合成演示数据。' },
  employeePosition: { title: '员工岗位', purpose: '指定员工档案的主要岗位。', sourceOrDefault: '来自本机岗位字典。', impact: '用于员工档案识别；可适用岗位与产线需在资格关系页单独维护。', limitation: '岗位选择不自动创建产线资格。' },
  employeeTeam: { title: '所属班组', purpose: '关联员工与本机班组档案。', sourceOrDefault: '来自有效班组目录，可不选择。', impact: '影响班组成员统计和对象选择。', limitation: '不改变既有 MIP 排班输入。' },
  employeeSkills: { title: '技能及评分', purpose: '维护员工的技能名称、编码和评分。', sourceOrDefault: '本机维护；演示技能标注为合成数据。', unit: '0–100 分', impact: '技能评分为有效且已评分技能的算术平均值。', limitation: '无评分时展示“无可计算值”，不按 0 处理。' },
  employeeCollaboration: { title: '协作评分', purpose: '记录本机维护的协作评价分值。', sourceOrDefault: '由维护人员填写，可留空。', unit: '0–100 分', impact: '仅在技能评分与协作评分均存在时计算综合评分。', limitation: '不是正式绩效或员工调查结果。' },
  teamId: { title: '班组编号', purpose: '唯一标识本机班组。', sourceOrDefault: '创建时由系统生成。', impact: '供员工、资格与轮转配置引用。', limitation: '编号为本机标识，不对应外部系统编码。' },
  teamName: { title: '班组名称', purpose: '提供班组业务可读名称。', sourceOrDefault: '由维护人员填写。', impact: '用于班组列表、成员管理和日历展示。', limitation: '名称不得为空。' },
  teamMembers: { title: '班组成员', purpose: '选择归属于当前班组的有效员工。', sourceOrDefault: '来自本机未归档员工档案。', unit: '人', impact: '保存时批量更新成员归属；员工从本班组移除后变为未分配，选入本班组的员工从原班组转入。', limitation: '每名员工只能归属一个班组；该关系仅用于本机成员管理和轮转日历，不修改 MIP 求解输入。' },
  teamDescription: { title: '班组说明', purpose: '记录班组用途或适用范围补充说明。', sourceOrDefault: '由维护人员填写，可留空。', impact: '仅用于本机维护与复核。', limitation: '不自动转为排班约束。' },
  qualificationObjectType: { title: '资格对象类型', purpose: '指定岗位资格关系关联到班组或员工。', sourceOrDefault: '由维护人员选择。', impact: '决定关联对象选项。', limitation: '对象须存在且有效。' },
  qualificationObject: { title: '资格对象', purpose: '选择拥有该岗位产线资格的员工或班组。', sourceOrDefault: '来自所选对象类型的本机有效目录。', impact: '轮转配置启用时据此验证对象的产线资格。', limitation: '资格记录仅为本机配置，不等同证书认证。' },
  qualificationLine: { title: '资格产线', purpose: '指定岗位资格适用的产线。', sourceOrDefault: '来自本机产线目录。', impact: '轮转对象只有具备对应产线资格时才允许启用。', limitation: '不是 MES 设备能力接口。' },
  qualificationPosition: { title: '资格岗位', purpose: '指定对象在所选产线可承担的岗位。', sourceOrDefault: '来自本机岗位字典。', impact: '用于展示岗位适用关系及配置校验。', limitation: '不自动加入 MIP 候选集。' },
  qualificationDescription: { title: '资格说明', purpose: '记录资格关系的本机维护说明。', sourceOrDefault: '由维护人员填写，可留空。', impact: '便于复核资格关系来源和边界。', limitation: '不得表述为外部资质系统已验证。' },
  rotationFilter: { title: '列表筛选', purpose: '按关键词、产线、班组或状态缩小本机目录范围。', sourceOrDefault: '默认显示第 1 页有效记录。', impact: '筛选只影响当前列表结果。', limitation: '不会修改业务记录。' },
  rotationSave: { title: '保存配置', purpose: '提交通过字段校验的本机配置或档案变更。', sourceOrDefault: '保存前执行服务端字段校验。', impact: '成功后写入本机 SQLite 并记录操作原因。', limitation: '配置保存与 MIP 求解输入相互独立。' },
  rotationCancel: { title: '取消编辑', purpose: '关闭当前抽屉并放弃尚未提交的表单修改。', sourceOrDefault: '不需要填写原因。', impact: '不会修改本机数据库。', limitation: '已保存的历史变更不会撤销。' },
  rotationArchive: { title: '停用或归档', purpose: '保留历史记录并停止其后续使用。', sourceOrDefault: '由维护人员执行并填写原因。', impact: '有效目录和日历不再使用已停用记录。', limitation: '不物理删除历史记录。' },
  rotationShiftStart: { title: '开始时间', purpose: '确定班次在业务日的开始时刻。', sourceOrDefault: '按 24 小时制填写 HH:mm。', unit: 'h:mm', impact: '决定日历中的班次起始时刻和跨日归属。', limitation: '与结束时刻相同会被服务端拒绝。' },
  rotationShiftEnd: { title: '结束时间', purpose: '确定班次结束时刻。', sourceOrDefault: '按 24 小时制填写 HH:mm。', unit: 'h:mm', impact: '早于开始时刻时，日历结束日期按次日处理。', limitation: '与开始时刻相同会被服务端拒绝。' },
  rotationShiftRemarks: { title: '班次说明', purpose: '补充班次的本机说明。', sourceOrDefault: '维护人员填写，可留空。', impact: '用于配置复核，不改变周期计算。', limitation: '最多 120 个字符。' },
  rotationAddShift: { title: '新增班次', purpose: '向当前配置增加一种可供周期日选择的班次。', sourceOrDefault: '新增后须填写唯一编码、名称和有效时间。', impact: '可在周期明细中被引用。', limitation: '至少保留一项有效班次定义。' },
  rotationRemoveItem: { title: '移除行', purpose: '从尚未保存的编辑表单中移除该行。', sourceOrDefault: '只作用于当前未提交表单。', impact: '保存后才会更新本机配置内容。', limitation: '移除被周期明细引用的班次后需重新选择。' },
  rotationRestDay: { title: '休息日', purpose: '将当前周期日设为不安排班次。', sourceOrDefault: '由配置创建人按周期制度设置。', impact: '日历显示“休息”，该日不关联班次时段。', limitation: '休息日不得同时选择班次。' },
  rotationUpdatedAt: { title: '更新时间', purpose: '显示本机数据库中该记录最近一次写入的时间。', sourceOrDefault: '由服务端在创建或更新时生成。', unit: 'Asia/Shanghai 本机时间', impact: '用于记录维护先后顺序。', limitation: '不是外部系统同步时间。' },
  employeeSkillCode: { title: '技能编码', purpose: '标识一项员工技能。', sourceOrDefault: '由维护人员填写。', impact: '用于区分技能条目并保存评分。', limitation: '同一档案内不应重复。' },
  employeeSkillName: { title: '技能名称', purpose: '提供技能的业务名称。', sourceOrDefault: '由维护人员填写。', impact: '用于员工档案展示和技能均分解释。', limitation: '不得将未核实技能表述为外部认证。' },
  employeeSkillActive: { title: '技能有效状态', purpose: '指定技能条目是否参与当前技能均分。', sourceOrDefault: '新增技能默认为有效。', impact: '仅有效且存在评分的技能进入均分。', limitation: '停用技能保留于档案但不参与评分。' },
  employeeSearch: { title: '员工筛选', purpose: '按员工编号或姓名缩小档案列表。', sourceOrDefault: '默认显示未归档员工。', impact: '只改变目录检索范围。', limitation: '员工编号精确查找建议使用完整编号。' },
  rotationCalendarView: { title: '日历视图', purpose: '切换月视图或周视图。', sourceOrDefault: '默认显示当前月份。', impact: '只改变日历展示范围，不更新配置。', limitation: '每次日历请求最多包含 62 个自然日。' },
  rotationCalendarPrevious: { title: '上一个周期', purpose: '将日历定位到前一个月或前一周。', sourceOrDefault: '根据当前显示方式确定步长。', impact: '触发对应日期范围的即时查询。', limitation: '不会修改任何轮班配置。' },
  rotationCalendarNext: { title: '下一个周期', purpose: '将日历定位到后一个月或后一周。', sourceOrDefault: '根据当前显示方式确定步长。', impact: '触发对应日期范围的即时查询。', limitation: '不会修改任何轮班配置。' },
  rotationStatus: { title: '记录状态', purpose: '显示配置、员工、班组或资格关系是否有效。', sourceOrDefault: '由本机维护操作更新。', impact: '停用或归档记录不会作为新轮转对象使用。', limitation: '状态不是外部系统认证结果。' },
  employeeCompositeScore: { title: '综合评分', purpose: '汇总技能均分与协作评分，用于本机员工画像展示。', sourceOrDefault: '由服务端按两项可计算评分的算术平均值生成。', unit: '0–100 分', impact: '仅在技能均分和协作评分均存在时提供数值。', limitation: '不代表正式绩效评价或模型预测概率。' },
  employeeEquipment: { title: '设备能力关系', purpose: '展示一名员工在本机设备目录中的多设备操作能力等级。', sourceOrDefault: '设备目录取自包内设备岗位参考清单；人员能力等级为本机仿真资料或维护人员配置。', impact: '仅用于档案查询、筛选和人员能力说明，不作为 MIP 求解输入。', limitation: '不构成岗位证书或现场能力核验结果。' },
  equipmentFilter: { title: '设备筛选', purpose: '按适用产线、设备编码、设备名称或设备类别缩小设备及员工列表。', sourceOrDefault: '设备选项来自本机参考清单并限定到本机已登记产线。', impact: '只改变当前目录显示范围。', limitation: '设备关系仍须符合员工有效产线资格。' },
  equipmentCode: { title: '设备编码', purpose: '标识参考目录中的具体设备类型及其本机产线记录。', sourceOrDefault: '来自包内岗位设备参考清单。', impact: '用于设备查询、选择和关系唯一性校验。', limitation: '不代表现场设备资产编号或联网状态。' },
  equipmentCategory: { title: '设备类别', purpose: '说明设备在本机参考目录中的分类。', sourceOrDefault: '来自包内岗位设备参考清单。', impact: '可用于缩小设备选择范围。', limitation: '目录未映射到本机产线的设备不提供分配选项。' },
  equipmentLine: { title: '设备适用产线', purpose: '限定设备能力关系可配置到的本机产线。', sourceOrDefault: '由包内源产线编码映射到本机轮转产线。', impact: '员工须具备该产线的有效资格关系方可保存。', limitation: '该映射为本机参考数据，不代表 MES 资产关系。' },
  equipmentAbilityLevel: { title: '设备能力等级', purpose: '记录员工对所选设备的本机能力分级。', sourceOrDefault: '可选整数 1 至 5 级，由本机维护人员配置。', unit: '级', impact: '作为人员档案的设备能力标签展示和筛选依据。', limitation: '等级含义为演示口径，不是证书核验或求解权重。' },
  equipmentAdd: { title: '添加设备', purpose: '将目录中一项设备加入当前员工的设备能力清单。', sourceOrDefault: '仅显示员工已登记有效资格的本机适用产线设备。', impact: '新增关系须填写能力等级并点击保存后生效。', limitation: '不能通过该操作新增或变更岗位产线资格。' },
  equipmentRemove: { title: '移除设备关系', purpose: '从未提交的人员设备清单中移除一项关系。', sourceOrDefault: '仅影响当前抽屉内待保存的数据。', impact: '点击保存后移除当前关系并将变更写入本机审计记录。', limitation: '取消或关闭抽屉不会保存移除操作。' },
  equipmentReason: { title: '设备关系变更原因', purpose: '说明新增、调整或移除员工设备关系的业务依据。', sourceOrDefault: '每次保存由维护人员填写。', impact: '与操作人和变更前后内容共同写入本机审计记录。', limitation: '不得填写密码、访问令牌等敏感信息。' },
  equipmentConfigure: { title: '配置设备', purpose: '查看或维护员工与一台或多台设备之间的能力关系。', sourceOrDefault: '员工设备关系保存在本机 SQLite 管理库。', impact: '保存后更新人员列表，并写入本机审计记录；产线资格失效或设备停用的既有关系须先显式移除。', limitation: '失效关系持续可见，不会被界面自动删除；不修改员工通用技能、轮转日历或 MIP 求解数据。' },
  teamMemberCount: { title: '有效成员数', purpose: '显示当前归属该班组且未归档的员工档案数量。', sourceOrDefault: '由本机员工档案实时汇总。', unit: '人', impact: '只读汇总值，不可在表格中直接修改。', limitation: '人员记录为演示数据或本机维护数据。' },
  teamLineCount: { title: '适用产线数', purpose: '统计班组拥有有效岗位资格关系的不同产线数量。', sourceOrDefault: '由本机资格关系实时汇总。', unit: '条产线', impact: '可用于识别班组已登记的轮转适用范围。', limitation: '不表示外部系统已校验产线技能。' },
  rotationRecordSource: { title: '记录来源', purpose: '标明记录由项目演示数据初始化或由本机用户维护。', sourceOrDefault: '由创建流程写入来源类型。', impact: '用于区分演示目录与后续本机配置。', limitation: '来源标签不证明外部数据真实或已联调。' },
  rotationShiftDisplayOrder: { title: '班次显示顺序', purpose: '规定班次在周期表单和日历中的展示次序。', sourceOrDefault: '按班次添加顺序自动写入。', impact: '仅影响界面呈现顺序，不改变班次时间或周期算法。', limitation: '当前界面按添加顺序保存。' },
  qualificationFilter: { title: '资格关系筛选', purpose: '按产线、岗位和对象类型筛选资格关系目录。', sourceOrDefault: '默认显示所有已登记关系。', impact: '只改变当前列表，不修改资格记录。', limitation: '筛选结果包含有效和停用关系。' },
  employeePositionFilter: { title: '员工岗位筛选', purpose: '按员工主要岗位缩小员工档案目录。', sourceOrDefault: '选项取自本机岗位字典。', impact: '只改变当前列表，不修改档案。', limitation: '主要岗位不等同于员工全部产线资格。' },
  employeeTeamFilter: { title: '员工班组筛选', purpose: '按所属班组缩小员工档案目录。', sourceOrDefault: '选项取自本机班组档案。', impact: '只改变当前列表，不修改班组或员工记录。', limitation: '未分配班组的员工需清除该筛选后查看。' },
};
